export enum RobofriendConstants {
  CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD",
  REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING",
  REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS",
  REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED",
}
